/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author viren
 */
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.coobird.thumbnailator.Thumbnails;
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form MainLogin
     */
    public MainLogin() {
        initComponents();
        conn=DBConnect.connectDB();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    
    public static int getLoginID(){
    return login_id;
    }
    
    public static void resetLoginId(){
    login_id=0;
    }
    
    public void loginStudent(){
    try {
            sql = "SELECT * FROM students WHERE student_username = ? AND student_password = ? ";
            preparedstatement=conn.prepareStatement(sql);
            preparedstatement.setString(1, txt_student_username.getText());
            preparedstatement.setString(2, txt_student_password.getText());
            rs=preparedstatement.executeQuery();
            if(rs.next()){
            login_id=rs.getInt("student_id");  
            user_role="student";
            //JOptionPane.showMessageDialog(null,"Login Success","Login",JOptionPane.INFORMATION_MESSAGE);
            //timer.start();
//            new EmployeeDetails().setVisible(true);
//            close();
            new student_home_page().setVisible(true);
            setVisible(false);
            }else{
            JOptionPane.showMessageDialog(null,"Login UnSuccess","Login",JOptionPane.INFORMATION_MESSAGE);
                  }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"SQLException in loginStudent method" +e.getMessage(),"Login",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Exception in loginStudent method" +e.getMessage(),"Login",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void loginLibrarian(){
        
        try {
            sql = "SELECT * FROM users WHERE user_name=? AND user_password=?";
            preparedstatement=conn.prepareStatement(sql);
            preparedstatement.setString(1, txt_librarian_username.getText());
            preparedstatement.setString(2, txt_librarian_password.getText());
            rs=preparedstatement.executeQuery();
            if(rs.next()){
            login_id=rs.getInt("user_id");    
            //JOptionPane.showMessageDialog(null,"Login Success","Login",JOptionPane.INFORMATION_MESSAGE);
            user_role="librarian";
            new librarian_home_page().setVisible(true);
                setVisible(false);
            //timer.start();
//            new EmployeeDetails().setVisible(true);
//            close();
            }else{
            JOptionPane.showMessageDialog(null,"Login UnSuccess","Login",JOptionPane.INFORMATION_MESSAGE);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Exception in loginLibrarian method"+e.getMessage(),"Login",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void registerStudent(){
    
        
        
        try {
            sql="SELECT * FROM students WHERE student_username=?";
             preparedstatement=conn.prepareStatement(sql);
            preparedstatement.setString(1, txt_new_username.getText());
            rs=preparedstatement.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null,"Username already exists");
            }
            else{
            String sql="INSERT INTO students(student_name,student_username,student_password,student_branch,student_email,student_contact,student_image) VALUES (?,?,?,?,?,?,?)";
            preparedstatement=conn.prepareStatement(sql);
            preparedstatement.setString(1, txt_new_name.getText());
            preparedstatement.setString(2, txt_new_username.getText());
            preparedstatement.setString(3, txt_new_password.getText());
            preparedstatement.setString(4, txt_new_branch.getText());
            preparedstatement.setString(5, txt_new_email.getText());
            preparedstatement.setString(6, txt_new_contact.getText());
            preparedstatement.setBytes(7, byteImage);
            preparedstatement.execute();
            
            sql="SELECT * FROM students WHERE student_username=?";
             preparedstatement=conn.prepareStatement(sql);
            preparedstatement.setString(1, txt_new_username.getText());
            rs=preparedstatement.executeQuery();
            if(rs.next()){
            login_id=rs.getInt("student_id");
            user_role="student";
            //JOptionPane.showMessageDialog(null,"Login Success : "+login_id);
            new student_home_page().setVisible(true);
            setVisible(false);
            }
            }
        } catch (Exception e) {
            
        JOptionPane.showMessageDialog(null,"Issue in registerStudent : "+e.getMessage());
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        tab_student_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_student_login = new javax.swing.JButton();
        txt_student_username = new javax.swing.JTextField();
        txt_student_password = new javax.swing.JPasswordField();
        tab_librarian_login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_librarian_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_librarian_password = new javax.swing.JPasswordField();
        btn_librarian_login = new javax.swing.JButton();
        tab_student_register = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_new_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_new_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_new_password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txt_new_branch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_new_email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_new_contact = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_upload_image = new javax.swing.JButton();
        txt_image_path = new javax.swing.JTextField();
        lbl_view_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        btn_student_login.setText("Login");
        btn_student_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_student_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_student_loginLayout = new javax.swing.GroupLayout(tab_student_login);
        tab_student_login.setLayout(tab_student_loginLayout);
        tab_student_loginLayout.setHorizontalGroup(
            tab_student_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_student_loginLayout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addGroup(tab_student_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_student_password, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tab_student_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab_student_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addComponent(txt_student_username, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tab_student_loginLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btn_student_login, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(138, 138, 138))
        );
        tab_student_loginLayout.setVerticalGroup(
            tab_student_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_student_loginLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_student_username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_student_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_student_login, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Student Login", tab_student_login);

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        btn_librarian_login.setText("Login");
        btn_librarian_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_librarian_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_librarian_loginLayout = new javax.swing.GroupLayout(tab_librarian_login);
        tab_librarian_login.setLayout(tab_librarian_loginLayout);
        tab_librarian_loginLayout.setHorizontalGroup(
            tab_librarian_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_librarian_loginLayout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addGroup(tab_librarian_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_librarian_loginLayout.createSequentialGroup()
                        .addGroup(tab_librarian_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_librarian_password, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_librarian_username, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_librarian_loginLayout.createSequentialGroup()
                        .addComponent(btn_librarian_login, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
        );
        tab_librarian_loginLayout.setVerticalGroup(
            tab_librarian_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_librarian_loginLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_librarian_username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_librarian_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_librarian_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Librarian Login", tab_librarian_login);

        jLabel5.setText("Name");

        jLabel6.setText("Username");

        jLabel7.setText("Password");

        jLabel9.setText("Branch");

        jLabel10.setText("Email");

        jLabel12.setText("Contact No");

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        btn_upload_image.setText("Upload Image");
        btn_upload_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upload_imageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_student_registerLayout = new javax.swing.GroupLayout(tab_student_register);
        tab_student_register.setLayout(tab_student_registerLayout);
        tab_student_registerLayout.setHorizontalGroup(
            tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_student_registerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_student_registerLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tab_student_registerLayout.createSequentialGroup()
                        .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(txt_new_name, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(txt_new_username)
                                .addComponent(txt_new_password))
                            .addComponent(jLabel9)
                            .addComponent(txt_new_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_new_email, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_student_registerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(tab_student_registerLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(lbl_view_image, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(139, Short.MAX_VALUE))))
                    .addGroup(tab_student_registerLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_upload_image)
                        .addGap(207, 207, 207))
                    .addGroup(tab_student_registerLayout.createSequentialGroup()
                        .addComponent(txt_new_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        tab_student_registerLayout.setVerticalGroup(
            tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_student_registerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tab_student_registerLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_new_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(txt_new_username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(lbl_view_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_new_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btn_upload_image))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_new_email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_student_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_new_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_register))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Register", tab_student_register);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_student_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_student_loginActionPerformed
        // TODO add your handling code here:
        loginStudent();
    }//GEN-LAST:event_btn_student_loginActionPerformed

    private void btn_librarian_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_librarian_loginActionPerformed
        // TODO add your handling code here:
        loginLibrarian();
    }//GEN-LAST:event_btn_librarian_loginActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        registerStudent();
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_upload_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upload_imageActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File sourcefile=fc.getSelectedFile();
        
        if(sourcefile != null){
        String path = sourcefile.getAbsolutePath();
        txt_image_path.setText(path);
        
            try {
                
                BufferedImage thumbnail=Thumbnails.of(sourcefile).size(180,200).asBufferedImage();
                ByteArrayOutputStream os=new ByteArrayOutputStream();
                ImageIO.write(thumbnail, "jpg", os);
                byteImage=os.toByteArray();
                viewImage = new ImageIcon(byteImage);
                lbl_view_image.setIcon(viewImage);
                
            } catch (Exception e) {
            }
        }
        
    }//GEN-LAST:event_btn_upload_imageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_librarian_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_student_login;
    private javax.swing.JButton btn_upload_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_view_image;
    private javax.swing.JPanel tab_librarian_login;
    private javax.swing.JPanel tab_student_login;
    private javax.swing.JPanel tab_student_register;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txt_image_path;
    private javax.swing.JPasswordField txt_librarian_password;
    private javax.swing.JTextField txt_librarian_username;
    private javax.swing.JTextField txt_new_branch;
    private javax.swing.JTextField txt_new_contact;
    private javax.swing.JTextField txt_new_email;
    private javax.swing.JTextField txt_new_name;
    private javax.swing.JPasswordField txt_new_password;
    private javax.swing.JTextField txt_new_username;
    private javax.swing.JPasswordField txt_student_password;
    private javax.swing.JTextField txt_student_username;
    // End of variables declaration//GEN-END:variables
    private Connection conn;
    private String sql;
    private PreparedStatement preparedstatement;
    private ResultSet rs;
    private static int login_id=0;
    private ImageIcon viewImage;
    private byte[] byteImage=null;
    private String user_role="";
}
